services:
  redis:
    image: redis:latest
    container_name: proxy_server_redis
    ports:
      - "6379:6379"
    env_file:
      - path: .env
        required: true
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --loglevel warning

volumes:
  redis_data:  # Defines the volume used to store Redis data.