version: '3'

tasks:
  start-app-containers:
    cmds:
      - docker-compose up -d
  server-one:
    dir: ./cmd/server_one
    cmds:
      - go run main.go
    silent: true
  server-two:
    dir: ./cmd/server_two
    cmds:
      - go run main.go
    silent: true
  proxy-server:
    dir: .
    cmds:
      - go run ./cmd/proxy_server/main.go
    silent: true
  doc-server:
    cmds:
      - godoc -http=:6060
  token-bucket-refill:
    dir: .
    cmds:
      - go run ./cmd/token_bucket_refiller/main.go
    silent: true


  start-servers:
    deps: [doc-server, server-one, server-two, proxy-server]
